name: Atualizar Data do README.md

on:
  schedule:
    - cron: '00 21 * * *' # Executar diariamente à meia-noite no horário de São Paulo Brasil
  
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Executar script de atualização da data
        run: |
          chmod +x ./update-date.sh
          ./update-date.sh
