name: Atualizar Data

on:
  schedule:
    - cron: '0 0 * * *' # Executar diariamente à meia-noite UTC
defaults:
  run:
    shell: bash
    
jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main # Specify the branch to pull from
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull changes from remote repository
        run: git pull https://github.com/rcDeveloping/endangeredBrazilianPlantSpecies.git main
      
      - name: Executar script de atualização da data
        run: |
          cd ..
          cd ..
          chmod +x update-date.sh
          git remote set-url origin https://github.com/"${{ github.actor }}"/endangeredBrazilianPlantSpecies.git
          git config --global user.email "rcflorestal@yahoo.com.br"
          git config --global user.name "${{ github.actor }}"
          git pull https://github.com/"${{ github.actor }}"/endangeredBrazilianPlantSpecies.git main
          ./update-date.sh
          git push https://github.com/"${{ github.actor }}"/endangeredBrazilianPlantSpecies.git main
          echo "${{ github.actor }}"
          echo "${{ secrets.GITHUB_TOKEN }}"
          
        working-directory: ${{ github.workspace }}

