name: Atualizar Data

on:
  schedule:
    - cron: '0 0 * * *' # Executar diariamente à meia-noite UTC

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Executar script
      run: |
        chmod +x update-date.sh
        ./update-date.sh
