name: Atualizar Data

on:
  schedule:
    - cron: '0 0 * * *' # Executar diariamente à meia-noite UTC

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configurar identidade do usuário Git
        run: |
          git config --global user.email "rcflorestal@yahoo.com.br"
          git config --global user.name "rcDeveloping"
        
      - name: Pull changes from remote repository
        run: git pull origin main


      - name: Executar script de atualização da data
        run: |
          chmod +x update-date.sh
          ./update-date.sh
        working-directory: ${{ github.workspace }}
